---
- name: Configure Java Application Server
  hosts: app

  user: vagrant
  become: yes

  vars:
    - dbhost: "db"
    - dbname: "notes"
    - dbusername: "notesapps"
    - dbpassword: "devops"
  tasks:
    - name: Configure hosts
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}" 
      with_items:
        - 192.168.56.2 control-node
        - 192.168.56.3 app
        - 192.168.56.4 db
    - name: Add app user
      user:
        name: app
        comment: application user
        uid: 500
    - name: Maven Instalation
      apt:
        name: maven
        state: latest
    - name: Java Instalation
      apt:
        name: java-1.8.0-openjdk
        state: latest
    - name: Create Directory app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: Clone repository notes - app
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configure property archive for database
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Gerate application package
        command: mvn -f /opt/notes/pom.xml package
        become_user: app
    - name: Register package latest version
      shell:
        cmd: mvn -o -q -Dexec.executable=echo -Dexec.args='${project.version}'
        chdir: /opt/notes/
      register: app_version
    - name: Configure Systemd Service
      template:
        src: etc/systemd/system/notes.service
        src: /etc/systemd/system/notes.service
        notify: reload daemon
    - name: start service notes
      service:
        notes: notes
        state: restarted
  roles:
    - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes