---
- name: Cofigure db server
  hosts: db

  user: vagrant
  become: yes #root
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db"
    - dbusername: "root"
    - dbpassword: "devops" 
  tasks:
    - name: Configure hosts lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}" 
      with_items:
        - 192.168.56.2 control-node
        - 192.168.56.3 app
        - 192.168.56.4 db
  roles: 
    - configure-default-so
    - role: geerlingguy.mysql